declare module "ol/control" { export default ol.control; }
declare module "ol/feature" { export default ol.Feature; }
declare module "ol/geom/point" { export default ol.geom.Point; }
declare module "ol/layer/tile" { export default ol.layer.Tile; }
declare module "ol/layer/vector" { export default ol.layer.Vector; }
declare module "ol/map" { export default ol.Map; }
declare module "ol/proj" { export default ol.proj; }
declare module "ol/source/osm" { export default ol.source.OSM; }
declare module "ol/overlay" { export default ol.Overlay; }
declare module "ol/source/vector" { export default ol.source.Vector; }
declare module "ol/style/circle" { export default ol.style.Circle; }
declare module "ol/style/fill" { export default ol.style.Fill; }
declare module "ol/style/stroke" { export default ol.style.Stroke; }
declare module "ol/style/style" { export default ol.style.Style; }
declare module "ol/view" { export default ol.View; }
